name = "GmshTools"
uuid = "82e2f556-b1bd-5f1a-9576-f93c0da5f0ee"
authors = ["Pengcheng Shi"]
version = "0.5.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
gmsh_jll = "630162c2-fc9b-58b3-9910-8442a8a132e6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
